# ==============================================================================
# Terminador TLS Interno (Stream L4): sensorhub (mqtt.sensorhub.andy.net.ar)
# Escucha interna: 127.0.0.1:10001 -> Destino remoto: 10.10.1.4:1883
# ==============================================================================

server {
    listen 127.0.0.1:10001 ssl;

    ssl_certificate     /etc/letsencrypt/live/sensorhub.andy.net.ar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sensorhub.andy.net.ar/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_session_cache shared:SSL_TCP_sensorhub_10001:10m;
    ssl_session_timeout 4h;

    proxy_timeout 1h;
    proxy_connect_timeout 10s;

    proxy_pass 10.10.1.4:1883;
}
