version = 5.8.0
archive_dir = /etc/letsencrypt/archive/sensorhub.andy.net.ar
cert = /etc/letsencrypt/live/sensorhub.andy.net.ar/cert.pem
privkey = /etc/letsencrypt/live/sensorhub.andy.net.ar/privkey.pem
chain = /etc/letsencrypt/live/sensorhub.andy.net.ar/chain.pem
fullchain = /etc/letsencrypt/live/sensorhub.andy.net.ar/fullchain.pem
[renewalparams]
account = 207a50deaa559784335fb146212bb839
authenticator = dns-cloudflare
dns_cloudflare_propagation_seconds = 30
dns_cloudflare_credentials = /etc/letsencrypt/cloudflare.ini
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-09-14T05:02:40
